package:
  name: eqlib
  version: {{ load_setup_py_data().version }}

source:
  git_rev:
  git_url: https://github.com/oberbichler/EQlib

requirements:
  build:
    - cmake>=3.14
    - mkl-devel>=2019.3
    - numpy>=1.16.2
    - python>=3.7.3
    - setuptools>=41.0.1
    - tbb-devel>=2019.4

  run:
    - mkl>=2019.3
    - python>=3.7.3
    - tbb>=2019.4

about:
  home: https://github.com/oberbichler/EQlib