name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user -r requirements.txt
        pip install hyperjet
    - name: Find
      run: |
        find / -name mkl.h 2>/dev/null
        find / -name libmkl_rt.so 2>/dev/null
    - name: Install package
      run: |
        pip install .
        python -c "import eqlib; print('eqlib._USE_MKL =', eqlib._USE_MKL)"
      shell: pwsh
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
