name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Print
      run: |
        from sysconfig import get_paths
        import os
        info = get_paths()
        data = info['data']
        os.environ['PATH'] = data + '/include' + os.pathsep + os.environ['PATH']
        print(os.environ)
      shell: python
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        echo $AGENT_TOOLSDIRECTORY
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install hyperjet
    - name: Install package
      run: |
        pip install .
        python -c "import eqlib; print('eqlib._USE_MKL =', eqlib._USE_MKL)"
      shell: pwsh
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
