name: Python package

on: [push]

jobs:
  build_windows_conda:
    name: build (windows-latest, conda)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Activate conda
      run: |
        call $CONDA/bin/activate
      shell: cmd
    - name: Install dependencies
      run: |
        conda install mkl-devel numpy scipy tbb-devel
        python -m pip install --upgrade pip
        pip install hyperjet
      shell: cmd
    - name: Install package
      run: |
        pip install .
      shell: cmd
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
      shell: cmd
      
  build_linux:
    name: build (ubuntu-latest, conda)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Activate conda
      run: |
        source $CONDA/bin/activate
    - name: Install dependencies
      run: |
        conda install mkl-devel numpy scipy tbb-devel
        pip install hyperjet
    - name: Install package
      run: |
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install package
      run: |
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
